### ISSUE TITLE
Remove extractMetadataSync()

### ISSUE THREAD

**Issue by quyin** [ecologylab/NewBigSemantics#13]
The extraction process is async in nature (e.g. calling a web service to filter locations, to parse citations, and to log).

Therefore this sync function will be removed. Use the async version, `extractMetadata()`, instead.

The whole repository needs to be searched through, in case someone is using this sync version.

**Comment by teschty** [comment]
Ah right, already changed everything to the async version in my local repo, just hadn't committed it yet.

**Comment by quyin** [comment]
cool. the hard part is to make sure that all other software (mice, extension, ideamache, tweetbubble, etc) work as expected. we'll need people to test it.

**Comment by quyin** [comment]
@teschty are you going to commit what you have (for this issue) soon, or there is some reason that prevents you from committing it?

**Comment by teschty** [comment]
@quyin oops sorry, should have updated this issue, I already did commit it.

**Comment by teschty** [comment]
And from an [organization wide search](https://github.com/search?q=org%3Aecologylab+extractMetadataSync&type=Code) (of what repos I have access to, and on master branch), I believe each listed instance has been replaced by the asynchronous equivalent on the dev branches (or removed).

**Comment by quyin** [comment]
cool!
