### ISSUE TITLE
Non-fatal build errors with ExtractorTest.ts

### ISSUE THREAD

**Issue by quyin** [ecologylab/NewBigSemantics#7]
when I build the project with `gulp` I'm getting a bunch of non-fatal build errors:

```
src/bscore/test/ExtractorTest.ts(45,1): error TS2304: Cannot find name 'describe'.
src/bscore/test/ExtractorTest.ts(48,3): error TS2304: Cannot find name 'it'.
src/bscore/test/ExtractorTest.ts(66,7): error TS2304: Cannot find name 'expect'.
```

they are related to the testing framework we are using, `jasmine`.

I wonder if there is a way to make the typescript compiler not to complain about them. one idea is to provide type definitions through `/// <reference>` element, so that the typescript compiler gets what it wants and the generated JS code remains the same.

**Comment by teschty** [comment]
Strange, I'm not getting those errors, and Jasmine does seem to be in the typings.json. Did you run typings to update it?

**Comment by quyin** [comment]
ah, my bad. after running `typings install` the errors go away.

thanks!

also, I installed Jasmine as a global package (`npm install jasmine -g`). is that supposed way of using Jasmine? or should it go into dev packages?

**Comment by teschty** [comment]
Oh right, probably dev packages unless gulp-jasmine requires it as global. I forgot to add that to the package.json.
